# Generated by Django 5.2 on 2025-10-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='fecha_registro',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='auth',
            old_name='apellido',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='auth',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='ultimo_login',
        ),
        migrations.AddField(
            model_name='auth',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
